quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://db-payment:5432/payment_db
quarkus.hibernate-orm.database.generation=update

quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.inventory-reserved.connector=smallrye-kafka
mp.messaging.incoming.inventory-reserved.topic=inventory-reserved-events
mp.messaging.incoming.inventory-reserved.group.id=payment-service-group
mp.messaging.incoming.inventory-reserved.value.deserializer=br.com.tcc.paymentservice.dtos.InventoryReservedDeserializer
mp.messaging.incoming.inventory-reserved.failure-strategy=dead-letter-queue
mp.messaging.incoming.inventory-reserved.dead-letter-queue.topic=inventory-reserved-dlq
mp.messaging.incoming.inventory-reserved.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.inventory-reserved.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.payment-processed.connector=smallrye-kafka
mp.messaging.outgoing.payment-processed.topic=payment-result-events
mp.messaging.outgoing.payment-processed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.payment-processed.retries=3
mp.messaging.outgoing.payment-processed.acks=all
mp.messaging.outgoing.payment-processed.kafka.retry.backoff.ms=1000
mp.messaging.outgoing.payment-processed.kafka.delivery.timeout.ms=10000
mp.messaging.outgoing.payment-processed.kafka.request.timeout.ms=5000

mp.messaging.outgoing.payment-failed.connector=smallrye-kafka
mp.messaging.outgoing.payment-failed.topic=payment-failed-events
mp.messaging.outgoing.payment-failed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.payment-failed.retries=3
mp.messaging.outgoing.payment-failed.acks=all
mp.messaging.outgoing.payment-failed.kafka.retry.backoff.ms=1000
mp.messaging.outgoing.payment-failed.kafka.delivery.timeout.ms=10000
mp.messaging.outgoing.payment-failed.kafka.request.timeout.ms=5000

quarkus.log.level=INFO
quarkus.log.category."br.com.tcc".level=DEBUG
quarkus.log.category."io.quarkus.rest.client".level=DEBUG

quarkus.log.console.enable=true
quarkus.log.console.level=DEBUG

quarkus.swagger-ui.always-include=true
quarkus.log.category."org.jboss.resteasy.reactive".level=DEBUG