quarkus.http.port=8082

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://db-payment:5432/payment_db
quarkus.hibernate-orm.database.generation=update

quarkus.log.level=INFO
quarkus.log.category."br.com.tcc".level=DEBUG
quarkus.log.category."io.quarkus.rest.client".level=DEBUG

quarkus.log.console.enable=true
quarkus.log.console.level=DEBUG

quarkus.swagger-ui.always-include=true
quarkus.log.category."org.jboss.resteasy.reactive".level=DEBUG